# Generated by Django 3.2.5 on 2023-01-05 00:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cer', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_com', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.cercle', verbose_name='Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_reg', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_vil', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.commune', verbose_name='Quartier/Village')),
            ],
        ),
        migrations.AddField(
            model_name='cercle',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.region', verbose_name='Cercle'),
        ),
    ]
