# Generated by Django 3.2.5 on 2022-03-12 01:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cer', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_com', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.cercle', verbose_name='Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_order', models.CharField(blank=True, max_length=30, verbose_name='Code order')),
                ('reception', models.BooleanField(default=True)),
                ('rendez_vous', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('create_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profil', verbose_name='Photo_commande')),
                ('status', models.CharField(choices=[('Client', 'CLIENT'), ('Ouvrier', 'OUVRIER'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], max_length=20)),
                ('type_tailleur', models.CharField(choices=[('Brodeur', 'BRODEUR'), ('Couture simple', 'COUTURE SIMPLE'), ('Couture a main', 'COUTURE A MAIN'), ('Boutouman', 'BUTTOUMAN'), ('Perleuse', 'PERLEUSE'), ('No qualifie', 'NO QUALIFIE')], max_length=20, verbose_name='Specialité')),
                ('genre', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME'), ('A', 'AUTRES')], max_length=20)),
                ('category', models.CharField(choices=[('G', 'GRANDE'), ('M', 'MOYENNE'), ('P', 'PETIT')], max_length=20)),
                ('code_person', models.CharField(blank=True, max_length=30, verbose_name='Code person')),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_1', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('domicile', models.CharField(blank=True, default='Lafiabougou', max_length=30, null=True)),
                ('alias', models.CharField(blank=True, max_length=30, null=True, verbose_name='alias')),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=8, null=True)),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('nationalite', models.CharField(blank=True, max_length=30, null=True)),
                ('tutuelle', models.CharField(blank=True, max_length=30, null=True)),
                ('telephonique_fix', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_reference', models.PositiveIntegerField(blank=True, null=True)),
                ('nina', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='Boubou', max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('code_product', models.CharField(max_length=30, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=100.25, max_digits=20, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_reg', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_vil', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.commune', verbose_name='Quartier/Village')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_payment', models.CharField(choices=[('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='Espece', max_length=50)),
                ('code_payment', models.CharField(blank=True, max_length=30, verbose_name='Code Payement')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Montant Total')),
                ('fees_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('payment_Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.order', verbose_name='Payment Facture')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Titulaire command')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Fille', 'Fille'), ('Garçon', 'Garçon'), ('Autres', 'Autres')], default='Homme', max_length=50)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('submontant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.product', verbose_name='Add Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='localization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.region', verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='contacts.Order_Items', verbose_name='add_items'),
        ),
        migrations.AddField(
            model_name='order',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Customer'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coude', models.FloatField(blank=True, null=True)),
                ('epaule', models.FloatField(blank=True, null=True)),
                ('manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('person_mesure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Mesure Client')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_payment_depense', models.CharField(choices=[('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='Espece', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Montant depensé')),
                ('pattern', models.CharField(choices=[('Paiement Ouvrier', 'Paiement Ouvrier'), ('Achat Materiel', 'Achat Materiel'), ('Paiement Magasin', 'Paiement Magasin'), ('Bon', 'Bon'), ('Electricite', 'Electricite')], default='Paiement Ouvrier', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description du depense')),
                ('status', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Titulaire Depense')),
            ],
        ),
        migrations.AddField(
            model_name='cercle',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.region', verbose_name='Cercle'),
        ),
    ]
