# Generated by Django 3.2.5 on 2021-08-05 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('PERSONNE', 'Personne'), ('SOCIETE', 'Societe')], max_length=30, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOM')),
                ('prenom', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRENOM')),
                ('matricule', models.CharField(blank=True, max_length=50, verbose_name='N°MATRICULE')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/identite', verbose_name='PHOTO IDENTITE')),
                ('contact', models.CharField(blank=True, max_length=8, null=True, verbose_name='TELEPHONE')),
                ('n_cin', models.CharField(blank=True, max_length=50, null=True, verbose_name='CIN')),
                ('nina', models.CharField(blank=True, max_length=50, null=True, verbose_name='NINA')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='PROFESSION')),
                ('rcimm', models.CharField(blank=True, max_length=50, null=True, verbose_name='REGISTRE DE COMMERCE')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('siege_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='SIEGE SOCIAL')),
                ('responsable', models.CharField(blank=True, max_length=50, null=True, verbose_name='RESPONSABLE')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ADRESSE EMAIL')),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_order', models.CharField(blank=True, max_length=30, verbose_name='Code commande')),
                ('reception', models.BooleanField(default=False)),
                ('rendez_vous', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profil/%d/%m/%Y', verbose_name='Photo_commande')),
                ('status', models.CharField(choices=[('Client', 'CLIENT'), ('Tailleur', 'TAILLEUR'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], default='CLIENT', max_length=20)),
                ('type_tailleur', models.CharField(choices=[('Brodeur', 'Brodeur'), ('Tailleur simple', 'TAILLEUR SIMPLE'), ('Tailleur simple', 'TAILLEUR SIMPLE'), ('Boutouman', 'BOUTOUMAN')], default='TAILLEUR SIMPLE', max_length=20)),
                ('sex', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autres')], default='Homme', max_length=20)),
                ('category', models.CharField(choices=[('G', 'Grande'), ('M', 'Moyenne'), ('P', 'Petite')], default='Grande', max_length=20)),
                ('code_person', models.CharField(blank=True, max_length=30, verbose_name='Code person')),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_1', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('domicile', models.CharField(blank=True, default='Lafiabougou', max_length=30, null=True)),
                ('alias', models.CharField(blank=True, max_length=30, null=True, verbose_name='alias')),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('nationalite', models.CharField(blank=True, max_length=30, null=True)),
                ('tutuelle', models.CharField(blank=True, max_length=30, null=True)),
                ('telephonique_fix', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_reference', models.PositiveIntegerField(blank=True, null=True)),
                ('nina', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Fille', 'Fille'), ('Garçon', 'Garçon'), ('Autres', 'Autres')], default='Homme', max_length=50)),
                ('name', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='Boubou', max_length=50)),
                ('code_produit', models.CharField(blank=True, max_length=30, verbose_name='Code Produit')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(upload_to='albums/%Y/%m/%d')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=50.25, max_digits=20, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('livre', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('paymentOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.order', verbose_name='Payment Facture')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Titulaire command')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BATI', 'Bati'), ('NON BATIE', 'Non Bati')], max_length=30)),
                ('area', models.PositiveIntegerField()),
                ('perimeter', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ManyToManyField(to='contacts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('submontant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.order', verbose_name='Commande')),
                ('product_id', models.ManyToManyField(to='contacts.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Titulaire Commande'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coude', models.FloatField(blank=True, null=True)),
                ('epaule', models.FloatField(blank=True, null=True)),
                ('manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('person_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Mesure Client')),
            ],
        ),
    ]
