# Generated by Django 3.2.5 on 2019-01-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ManyToManyField(to='contacts.Cercle', verbose_name='Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('type', models.CharField(choices=[('Broderie', 'Broderie'), ('Couture simple', 'COUTURE SIMPLE'), ('Couture a main', 'COUTURE A MAIN'), ('Finition', 'FINITION')], default='Broderie', max_length=20)),
                ('category', models.CharField(choices=[('G', 'Grande'), ('M', 'Moyenne'), ('P', 'Petite')], default='Grande', max_length=20)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autres')], default='Homme', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_order', models.CharField(blank=True, max_length=30, verbose_name='Code order')),
                ('reception', models.BooleanField(default=True)),
                ('rendez_vous', models.DateField(auto_now=True)),
                ('confirmed', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ManyToManyField(to='contacts.Commune', verbose_name='Village')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='Boubou', max_length=50)),
                ('code_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code Produit')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=100.25, max_digits=20, null=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('image', models.ManyToManyField(to='contacts.Image', verbose_name='ALBUM')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profil', verbose_name='Photo_commande')),
                ('status', models.CharField(choices=[('Client', 'CLIENT'), ('Tailleur', 'TAILLEUR'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], default='CLIENT', max_length=20)),
                ('type_tailleur', models.CharField(choices=[('Brodeur', 'Brodeur'), ('Tailleur simple', 'TAILLEUR SIMPLE'), ('Tailleur simple', 'TAILLEUR SIMPLE'), ('Boutouman', 'BOUTOUMAN')], max_length=20)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autres')], default='Homme', max_length=20)),
                ('category', models.CharField(choices=[('G', 'Grande'), ('M', 'Moyenne'), ('P', 'Petite')], default='Grande', max_length=20)),
                ('code_person', models.CharField(blank=True, max_length=30, verbose_name='Code person')),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_1', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('domicile', models.CharField(blank=True, default='Lafiabougou', max_length=30, null=True)),
                ('alias', models.CharField(blank=True, max_length=30, null=True, verbose_name='alias')),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=8, null=True)),
                ('date_naissance', models.DateField(auto_now_add=True)),
                ('nationalite', models.CharField(blank=True, max_length=30, null=True)),
                ('tutuelle', models.CharField(blank=True, max_length=30, null=True)),
                ('telephonique_fix', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_reference', models.PositiveIntegerField(blank=True, null=True)),
                ('nina', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_payment', models.CharField(choices=[('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='Homme', max_length=50)),
                ('code_payment', models.CharField(blank=True, max_length=30, verbose_name='Code Payement')),
                ('mount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Montant Total')),
                ('frees_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('livre', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('payment_Order', models.ManyToManyField(to='contacts.Order', verbose_name='Payment Facture')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Titulaire command')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Fille', 'Fille'), ('Garçon', 'Garçon'), ('Autres', 'Autres')], default='Homme', max_length=50)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('submontant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.product', verbose_name='Products')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='localization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.region', verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='contacts.Order_Items', verbose_name='add_items'),
        ),
        migrations.AddField(
            model_name='order',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Customer'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coude', models.FloatField(blank=True, null=True)),
                ('epaule', models.FloatField(blank=True, null=True)),
                ('manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('person_mesure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Mesure Client')),
            ],
        ),
        migrations.AddField(
            model_name='cercle',
            name='name',
            field=models.ManyToManyField(to='contacts.Region', verbose_name='Cercle'),
        ),
    ]
