# Generated by Django 3.1.5 on 2021-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N°MATRICULE'),
        ),
    ]
