# Generated by Django 3.2.5 on 2022-01-08 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cercle',
            name='id_cer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='id_com',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_reg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='id_vil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
