# Generated by Django 3.1.5 on 2021-01-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/identite', verbose_name='PHOTO IDENTITE'),
        ),
    ]
