# Generated by Django 3.2.5 on 2022-01-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Image',
        ),
    ]
