# Generated by Django 3.2.5 on 2019-01-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='id_cercle',
            new_name='id_cer',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='code_vill',
            new_name='code_village',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='id_com',
            new_name='id_commune',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='name_vill',
            new_name='name_village',
        ),
    ]
