# Generated by Django 3.2.5 on 2019-01-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190101_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='id_cer',
            new_name='id_cercle',
        ),
    ]
