# Generated by Django 3.2.5 on 2022-01-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='rendez_vous',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_payment',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='', max_length=50),
        ),
    ]
