# Generated by Django 3.1.5 on 2021-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210122_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='TELEPHONE'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='n_cin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NINA'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sexe',
            field=models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('PERSONNE', 'Personne'), ('SOCIETE', 'Societe')], max_length=30),
        ),
    ]
