# Generated by Django 3.2.5 on 2019-01-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_id_cer_commune_id_cercle'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='id_village',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
