# Generated by Django 3.2.5 on 2022-01-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20220119_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_payment',
            field=models.CharField(choices=[('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='Espece', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('G', 'GRANDE'), ('M', 'MOYENNE'), ('P', 'PETIT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='genre',
            field=models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME'), ('A', 'AUTRES')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Client', 'CLIENT'), ('Ouvrier', 'OUVRIER'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='type_tailleur',
            field=models.CharField(choices=[('Brodeur', 'BRODEUR'), ('Couture simple', 'COUTURE SIMPLE'), ('Couture a main', 'COUTURE A MAIN'), ('Boutouman', 'BUTTOUMAN'), ('Perleuse', 'PERLEUSE'), ('No qualifie', 'NO QUALIFIE')], max_length=20, verbose_name='Specialité'),
        ),
    ]
