# Generated by Django 3.2.5 on 2021-11-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211113_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='code_village',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
