# Generated by Django 3.2.5 on 2021-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_village_code_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
