# Generated by Django 3.2.5 on 2022-01-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20220122_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='contacts.Order_Items', verbose_name='add_items'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.commune', verbose_name='Quartier/Village'),
        ),
    ]
