# Generated by Django 3.2.5 on 2021-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20211113_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
