# Generated by Django 3.2.5 on 2023-04-29 01:16

from django.db import migrations, models
import django.db.models.deletion
import kalaliso.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.FileField(upload_to='photos/', validators=[kalaliso.validators.file_size])),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_order', models.CharField(blank=True, max_length=30, verbose_name='Code order')),
                ('reception', models.BooleanField(default=True)),
                ('rendez_vous', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('create_at', models.DateField()),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.region', verbose_name='Localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='Boubou', max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('code_product', models.CharField(max_length=30, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=100.25, max_digits=20, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.FileField(upload_to='video/%y', validators=[kalaliso.validators.file_size])),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('like', models.IntegerField()),
                ('shared', models.IntegerField()),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_payment', models.CharField(choices=[('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='Espece', max_length=50)),
                ('code_payment', models.CharField(blank=True, max_length=30, verbose_name='Code Payement')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Montant Total')),
                ('fees_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now=True)),
                ('payment_Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kalaliso.order', verbose_name='Payment Facture')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Fille', 'Fille'), ('Garçon', 'Garçon'), ('Autres', 'Autres')], default='Homme', max_length=50)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('submontant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.product', verbose_name='Add Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='kalaliso.Order_Items', verbose_name='add_items'),
        ),
        migrations.AddField(
            model_name='order',
            name='person_id',
            field=models.ManyToManyField(to='contacts.Person'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coude', models.FloatField(blank=True, null=True)),
                ('epaule', models.FloatField(blank=True, null=True)),
                ('manche_courte', models.FloatField(blank=True, null=True)),
                ('manche_longue', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Mesure Client')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode_payment_depense', models.CharField(choices=[('Espece', 'Espece'), ('Orange Money', 'Orange Money'), ('Mobi Cash', 'Mobi Cash'), ('Sama Money', 'Sama Money'), ('Wave', 'Wave'), ('Virement', 'Virement'), ('Transaction', 'Transaction')], default='Espece', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Montant depensé')),
                ('motif', models.CharField(choices=[('Paiement Ouvrier', 'Paiement Ouvrier'), ('Achat Materiels', 'Achat Materiels'), ('Paiement Magasin', 'Paiement Magasin'), ('Bon', 'Bon'), ('Electricite', 'Electricite')], default='Paiement Ouvrier', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description du depense')),
                ('status', models.BooleanField(default=False, verbose_name='valid')),
                ('cancelled', models.DateField()),
                ('create_at', models.DateField(auto_now=True)),
                ('person_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person', verbose_name='Titulaire Depense')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(choices=[('Or', 'Or'), ('Meduim', 'Medium'), ('Diamon', 'Diamon')], default='Or', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.album', verbose_name='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('video', models.FileField(blank=True, upload_to='video/%y', validators=[kalaliso.validators.file_size])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
            ],
        ),
    ]
